### ISSUE TITLE
reliance on yubikey API Server

### ISSUE THREAD

**Issue by joe-getcouragenow** [cromega/keyguard#1]
Curious why we cant just use the yubikey without needed an API key from yubikey ?

https://upgrade.yubico.com/getapikey/

Is it possible to run your server ?

I am curious if the answer is that the hardware keys sold by yubikey require getting an API Key from their server in order to talk to your own yubikey ?

**Comment by cromega** [comment]
@joe-getcouragenow it's certainly possible to run your own authentication server, in which case you can generate your own client ids.

See https://developers.yubico.com/OTP/Guides/Self-hosted_OTP_validation.html

and https://developers.yubico.com/yubikey-val/Generating_Clients.html

You only need an API key from yubico if you want to authenticate your key against the official service.
